version: "3.9"

services:
    mlworkshop:
        build: .
        volumes:
            - ./src:/tf
        ports:
            - "8888:8888"
            - "6006:6006"
            - "5000:5000"
        environment: 
            - MLFLOW_TRACKING_URI=http://localhost:5000